### ISSUE TITLE
dpi vs ppi

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#1]
[Comment]
Fingerprint Toolbox uses dpi for scanner resolution. I am not sure which one should be used but NIST SP 500-290e3 uses ppi for scanner resolution

[Proposed change]
Discuss and determine which one should be used for scanner resolution

**Comment by woodbe** [comment]
Well, just looking at a plain descriptive comparison, PPI is used specifically for digital, while DPI would only be used when printing output. That said, scanners usually seem to list DPI for their resolution, but that is probably more from convention than anything else. 

@gregott do you have a specific reason to have used DPI here vs PPI, or just "convention"?

I can't think of any references to DPI in the printing output (just "use highest quality"), so we would probably be OK just moving it all to PPI.

**Comment by gfiumara** [comment]
FBI's EBTS Appendix F, which is their standard for scanner certification (digitizing ink cards, as well as applied to live-scan tech) refers to fingerprint printers in DPI and scanners in PPI. I'd go for PPI.
