### ISSUE TITLE
Attack 2D Fingerprint 02-0X

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#12]
[Referenced section]
Penetration Testing Suggestion

[Comment]
_Copper cladding thickness can be varied to produce differing height ridges in the casts._

The above test should be indented.

According to *3), thickness like 105μm should be avoided. 
_9.1.5 PCB production
Epoxy laminates, which created copper thicknesses of 35 μm, 70 μm, and 105 μm were available. The 105 μm thickness was discarded since the very small details of the fingerprint were difficult to etch that thick._

*3) http://liu.diva-portal.org/smash/get/diva2:19729/FULLTEXT01

[Proposed change]
Indent the text and add a note to explain that thickness should be less than 70μm if *3) is true.

**Comment by gregott** [comment]
Yes, of the three thicknesses cited in Standstrom, 35 μm is approximately 1.38 mils which is roughly equivalent to the standard “1 oz” of copper.  70 μm is approximately 2.75 mils which is roughly “2 oz” of copper.  It is not recommended to use copper thicker than 2 oz / 2.75 mils / 70 μm.
