### ISSUE TITLE
Attack 2D Fingerprint 0X-02 Modeling compound cast

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#14]
[Referenced section]
Recipe - cast

[Comment]
_The test report shall specify which version is used._

What document of the version shall be reported? Version of Fingerprint Toolbox Inventory? But Fingerprint Toolbox Inventory has no version specified.

Or “version” should be replaced with “commercial equivalent”?

[Proposed change]
Clarify the text.

**Comment by woodbe** [comment]
I have edited this in all the attacks and it will be in the next PR I upload for attacks.
