### ISSUE TITLE
Attack 2D Fingerprint 02-03 - Total Number of Species

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#15]
[Referenced section]
Total Number of Species

[Comment]
Only this test requires to test 10 species.

[Proposed change]
Add reason why if this is not an editorial mistake

**Comment by woodbe** [comment]
@n-kai this was editorial. There had been confusion about species vs total number of PAI. The original docs all listed 10, but under the definitions we have been using, that is 10 PAI, but only 1 species as the species basically counted the number of variants in the test. I must have missed this one when I was moving things over.
