### ISSUE TITLE
Attack potential table - Elapsed Time for all attacks 

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#16]
[Referenced doc]
test items under attacks directory

[Comment]
Elapsed time for mold and cast in Identification Value are separately rated as 1, which means to create the PAI using both mold and cast take two weeks (i.e. Total elapsed time should be rated as 2).

[Proposed change]
Change elapsed time for mold and cast to, for example, 0.3 and 0.7 so that total elapsed time can be 1 (less than one week as described in the BIOSD)

**Comment by woodbe** [comment]
If #17 is done, then this wouldn't need to be done since there would only be one value, which would/could be 1, and we wouldn't worry about the split between the mold/cast portions.

**Comment by woodbe** [comment]
@woodbe will edit the 01-01 attack table into 3 tables based on call discussion for review.

**Comment by woodbe** [comment]
@n-kai will update the table for how the mold and cast AP should be calculated. @woodbe will update the table for the column with the component selection.

**Comment by woodbe** [comment]
Closing based on #48.
