### ISSUE TITLE
Fingerprint Verification List -- Contactless Column?

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Fingerprint-Toolbox#21]
Should we add a contactless/non-contact column to FINGERPRINT_Toolbox_Verification_List.adoc? To the best of my knowledge, there's no **first-party** device using integrated cameras to image a finger for _device unlock_. My initial thought is no, but wanted to raise the question.

**Comment by woodbe** [comment]
I would say not at this time. Doing it would probably be like some sort of Frankenstein of fingerprint and face that I think should wait until we have someone actually wanting to do it.

**Comment by woodbe** [comment]
Closed by agreement at this time on 11/19.  Will reopen if vendors request to use this type of functionality.
