### ISSUE TITLE
Image enhancement

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#3]
[Referenced Doc]
Fingerprint Toolbox Overview - 2.1.1. PAD data acquisition - Image enhancement and preparation
test items under attacks directory

[Comment]
Photo processing software is used only for flipping and inverting the fingerprint image in test items under attacks directory. Images are not improved in those items by using the software as described in this section. Image enhancement should be done for the image captured from latent fingerprint however it may not be necessary to enhance the image captured by the commercial fingerprint scanner.

[Proposed change]
Update the text to make this section (Image enhancement and preparation) and each test item consistent or add a note something like “image enhancement should be done for latent fingerprint image”.

**Comment by woodbe** [comment]
add cleaning of sensor, molds, fingers to minimize dust/scratches. Noise is more about presentation, so practice

cleaning everything and then using binarization software, then enough image processing to flip/invert colors = layman

**Comment by woodbe** [comment]
@n-kai I am thinking that this information about cleaning, scratches, etc should go under the section 4 for the common test protocol. Here I would add a section about "common testing hygiene" (or something to that effect) that would basically say that everything should be cleaned before use (by whatever method is appropriate for the item). I would then specify that this will reduce noise and provide clearer prints. A note about practice could also be added here.

Would it be OK to have it here? We really have a lot of duplicate content here, so I'm not sure if we should hold this off until we do a full review of the overview?

**Comment by n-kai** [comment]
@woodbe 
I think it's OK to have it under the section 4.
