### ISSUE TITLE
Overview: Process for thicker than normal cladding

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Fingerprint-Toolbox#34]
The overview cautions:
> Be sure to adjust the process as necessary for the thicker than normal copper cladding.

How does one adjust the process? We should add text that describes the adjustment, or remove this if it should be obvious to someone who deals with PCB. I have no experience here.

**Comment by gregott** [comment]
Thicker copper requires longer etching time.  This should be obvious to anyone who makes PCBs.  I think the sentence can be removed.
