### ISSUE TITLE
Mold made from transparency

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#4]
[Referenced doc]
Fingerprint Toolbox Overview - 4.1.1. Flat PAI mold preparation

[Comment]
Toolbox requires evaluator to create two types of flat mold, printed transparency and PCB, however, creation of good quality fingerprint PAIs is time-consuming task and the evaluator has to finish the penetration testing within one week. So it’s better to limit the number of PAIs so that the evaluator can spend more time to get used to create the PAIs.

Only PCB mold should be used because it can create higher quality PAIs than transparency (See *2)

*2) https://www.ccc.de/en/updates/2013/ccc-breaks-apple-touchid

[Proposed change]
Remove the requirement to create PAIs from transparency mold from fingerprint toolbox.

**Comment by gregott** [comment]
I agree that PCB based PAIs have the advantage over transparency PAIs of having a higher relief between the ridges and the valleys as indicating in the CCC article.  However, transparency based PAIs are much faster and easier to make.  I made PCBs as a teenager and PCB based PAIs more recently.  They do not take that long to learn how to make.  So having the two methods should not be a problem.  Besides, if a lab is going to get into the business of doing PAD testing, I would expect them to become familiar with the materials and methods of the toolboxes before they conduct their first evaluation.

**Comment by n-kai** [comment]
Thank you. If inexperienced evaluators can create PAIs from transparency easily, it should be no problem to use those PAIs for the toolbox testing.
