### ISSUE TITLE
When is mold release needed?

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Fingerprint-Toolbox#51]
Some of the attacks say:
 > If needed apply mold release to the target finger following the manufacturer instructions.

Can we suggest when this might be needed?

**Comment by gregott** [comment]
The need for mold releases is a case by case decision.  Some mold materials release some cast materials easily and not so easily for others.  I expect the evaluator will determine when releases are needed and then document which ones were used, when and how they were used.

**Comment by woodbe** [comment]
I think this is actually described earlier (2.2.2.1.1), though maybe we should add a note there about practicing? The current language states they may be needed, and if used documented, but nothing explicit about practicing to find out whether they would be needed or not.

**Comment by gregott** [comment]
I was assuming the "if needed" implied the evaluator was practicing/prepping for the real test and decided on the need for the release.  I should not assume.  I think adding a note would be good.
