### ISSUE TITLE
CSM 4: example for fingerprint deformation

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Fingerprint-Toolbox#59]
https://github.com/biometricITC/Fingerprint-Toolbox/blame/06896fdb6efabdb959c6e3190af76c2b9255057a/FINGERPRINT_Toolbox_Overview.adoc#L64

CSM 4: capturing curved fingerprint data means acquiring friction ridge data while the finger is not in contact with another object that causes the skin to deform - Better to explain this statement using a provided example.

Proposal: Could you give example of another object that causes the skin to deform

**Comment by woodbe** [comment]
@gregott I'm not exactly sure of another good example, hence the assigning to you.

**Comment by gregott** [comment]
This is in contrast to the previous section on Flat Attacks.  The platen of a fingerprint scanner causes the finger to flatten.  This is what I had in mind when writing this statement.

**Comment by woodbe** [comment]
How about this:

> ...capturing curved fingerprint data means acquiring friction ridge data while the finger is not in contact with another object that causes the skin to deform **_(as it would on a fingerprint scanner)_**.


just adding that phrase should provide the example. I do get what you are saying.

**Comment by gregott** [comment]
Sounds good to me.
