### ISSUE TITLE
Add ultrasonic sensor to Fingerprint Verification List

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#7]
[Referenced doc]
Fingerprint Verification List

[Comment]
Ultrasonic sensor should also be added in the table because some smartphones equip this type of sensor.

[Proposed change]
Add Ultrasonic sensors column to the table or replace “Optical Sensor” with “Optical/ Ultrasonic Sensor”.

**Comment by woodbe** [comment]
I will add this in my update.

**Comment by gfiumara** [comment]
I think it might be better to add a column for Ultrasonic rather than to have it share the Optical column. These are very different technologies. Although the columns might have the same content, I think it sends a clearer message to separate them.
