### ISSUE TITLE
Link error in Fingerprint Verification List

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#8]
[Comment]
All hyperlinks (e.g Fingerprint 01-01) don’t work.

[Proposed change]
Correct hyperlinks in Fingerprint Verification List

**Comment by woodbe** [comment]
I had sort of copied these over, but didn't take too much time since I wasn't sure if the links would need to change (tests added/combined, etc), so this will be a last step.

**Comment by woodbe** [comment]
To be clear, I think this should be done after the first round of comments since I think we will have changes to the tests at that time (consolidating test cases into variants, but I think it may be easier in the first round to see them individually).
