### ISSUE TITLE
Editorial mistake in toolbox inventory

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#9]
Fingerprint Toolbox Inventory - T.1　Cinferprint scanner
- "Cinferprint" should be changed to "fingerprint".

Fingerprint Toolbox Inventory - M.3　Eye Mimicry
- "Eye Mimicry" should be changed to "Dental Impression material"
- Remove "*"

**Comment by woodbe** [comment]
I saw these, they were copy/paste errors. I will fix them in the PR I'm working on.
