### ISSUE TITLE
determine best practice for pulling latent prints

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Fingerprint-Toolbox#90]
To attempt to standardize as best as possible for latent prints, create some steps around how to get it.

Probably look at FBI or similar to get something.

(example) https://archives.fbi.gov/archives/about-us/lab/forensic-science-communications/fsc/jan2001/lpu.pdf

https://assets.publishing.service.gov.uk/media/65d35b9e0f4eb10064a9810d/Fingermark_Visualisation_Manual_2nd_Edition_2022.pdf

Kevin stated that using screens or cards are most common with carbon powder.

**Comment by woodbe** [comment]
https://www.crimesciencetechnology.com/_files/ugd/4fa655_23ef6fc679e74a4ea5441eac969eb0d8.pdf

**Comment by n-kai** [comment]
PAD L1 can refer the following paper.
https://iris.unige.it/bitstream/11567/1083652/1/2020ICPR_spoof.pdf
I reviewed several papers but this "ScreenSpoof" may be the best way to create PAIs for PAD L1.
