### ISSUE TITLE
PCB Fabrication Kit Safety Note

### ISSUE THREAD

**Issue by DouglasKalmus** [biometricITC/Fingerprint-Toolbox#95]
The new materials (as of 9/17) include the following note:
|FP1-T.12
|Fingerprint Powder
|A granular powder containing fine granular particles (5-10 μm). **Be aware of safety needs for these powders.**

A similar note is also found in the inventory under "M.4 Moldable Plastic".

A similar safety note (for both disposal/storage/handling of chemicals) should be made for the chemicals involved with PCB etching.
Two of the most commonly used chemicals for PCB etching are Ferric Chloride and Cupric Chloride. Both of these chemicals require specific instructions for disposal, storage, and handling.

While the Toolbox doesn't need to go into specific detail, a note to consult the chemical manufacturer's guidance (or even a more generalized safety note) would be sufficient.

SDS for both as reference:
https://www.sigmaaldrich.com/US/en/sds/SIGALD/157740?userType=undefined
https://www.senturyreagents.com/msds/cupric_chloride_solution.pdf

**Comment by woodbe** [comment]
@DouglasKalmus please check that #97 works for what you have in mind.
