### ISSUE TITLE
Liquid Glue clarification

### ISSUE THREAD

**Issue by DouglasKalmus** [biometricITC/Fingerprint-Toolbox#96]
Although implied by "FP1-C.5 Glue Instructions", it should be noted under Commercial Examples - "FP1-C.5" that a "liquid" glue is expected. This will prevent confusion between solid and liquid glue types. For example, when searching Google for "Elmer's school glue" there are a handful of hits for the solid glue sticks which would not make sense to use here.

**Comment by woodbe** [comment]
@DouglasKalmus please check out #97 to see if that works for you.

**Comment by DouglasKalmus** [comment]
The updates look good to me. Thanks.
